#app
server:
    port: 8085

management:
  port: 9095
  security:
    enabled: false
  # Dubbo Health
  health:
    dubbo:
      status:
                defaults: memory
                extras: load,threadpool
  

# Dubbo Endpoint (default status is disable)
endpoints:
  dubbo:
    enabled: true


dubbo:
  application:
    qos:
      enable: true
      port: 33333
    
    name: orianna-service
    owner: sandi
    organization: mhc
  registry:
    address: zookeeper://zk.haimaiche.net:2181?backup=172.21.10.43:2181

  protocol:
    name: dubbo
    port: 20885
    host: 127.0.0.1
    
  provider:
    version: 1.0_local
    timeout: 5000

#      consumer:
#        buick:
#          version: 1.0_local
#          timeout: 15000
#          retries: 0
#          check: false
 
#spring
spring:
  application:
    name: orianna
    
  datasource:
    url: jdbc:mysql://daily-mhc-o.mysql.rds.aliyuncs.com:3306/db_assets_shixi?useUnicode=true&characterEncoding=utf-8
    username: assets_shixi
    password: MDk3MjZiNDcwY2Jh
    driver-class-name: com.mysql.jdbc.Driver
    
    druid: 
      initial-size: 5
      max-active: 20
      
  # REDIS (RedisProperties)
  redis:
    # Redis数据库索引（默认为0）
    #database: 0
    # Redis服务器地址
    host: yijiqingchen.com
    # Redis服务器连接端口
    port: 6399
    # Redis服务器连接密码（默认为空）
    password: zhimaguanmen
    pool: 
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 20
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
    timeout: 5000
    
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mhc.orianna.dal.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

swagger:
  title: orianna-service 网关应用接口
  version: V1.0.0
  base-package: com.mhc.orianna
  exclude-path:
    - /dubbo/*
    - /online/*
    - /offline/*
  contact:
    name: 三帝
    email: sandi@maihaoche.com
#  docket:
#    test:
#      title: Test
#      version: V1.0.0
#      base-package: com.mhc.gwcarlsson
#      base-path:
#        - /hello/*
#      contact:
#        name: A
#        email: a@maihaoche.com
#  
#    user:
#      title: User
#      version: V1.0.0
#      base-package: com.mhc.gwcarlsson
#      base-path:
#        - /user/*
#      contact:
#        name: B
#        email: b@maihaoche.com

#logging
logging:
  config: classpath:logback-spring.xml
  # 应用名称
  appname: ${spring.application.name}
  # 日志文件路径
  apppath: ${HOME}/app/logs
  level: 
    root: INFO
    spring: INFO
    dubbo: INFO
    mhcframework: INFO
    mhc: INFO
    